repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=80, --target-version=py39]
        exclude: ^(venv/|docs/)
        types: ["python"]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        args: [--max-line-length=80]
        exclude: ^(venv/|docs/)
        types: ["python"]
